package utils















































}	return runtime.GOOS == "windows"func IsWindows() bool {// IsWindows checks if running on Windows}	return runtime.GOOS == "darwin"func IsMacOS() bool {// IsMacOS checks if running on macOS}	return runtime.GOOS == "linux"func IsLinux() bool {// IsLinux checks if running on Linux}	return runtime.GOOSfunc GetPlatform() string {// GetPlatform returns the current platform}	return cmd.Run() == nil	cmd := exec.Command("which", shell)func IsValidShell(shell string) bool {// IsValidShell checks if a shell path is valid}	return "/bin/sh"	}		return "cmd.exe"	if runtime.GOOS == "windows" {	}		return shell	if shell != "" {	shell := os.Getenv("SHELL")func GetShell() string {// GetShell returns the default shell for the platform)	"runtime"	"os/exec"	"os"import (package utils